[project]
<<<<<<< HEAD
name = "droot"
version = "0.1.0"
=======
name = "Droots"
version = "0.1.3"
>>>>>>> 05f2ae0 (Fixed folder structure, missing entry point in PyPI, and inconsistent naming)
description = "Generate structured Python project folders instantly"
authors = [{ name = "Caleb M. Sibanda", email = "darkian.dev@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = []

[project.scripts]
<<<<<<< HEAD
droot = "droot:menu"

[tool.setuptools]
packages = ["src.droot", "src.droot.templates"]
package-dir = { "" = "src" }
=======
droots = "drt.cli:main"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["drt", "drt.templates"]
>>>>>>> 05f2ae0 (Fixed folder structure, missing entry point in PyPI, and inconsistent naming)

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"